import Head from 'next/head';
import { useEffect, useState } from 'react';
import styles from '@/styles/Home.module.css';

export default function Home() {
    useEffect(() => {
        const intro = document.getElementById('intro');
        const loop = document.getElementById('loop');
        const onlyAt = document.getElementById('onlyAt');
        const coming = document.getElementById('coming');
        if (intro && loop) {
            intro.play();
            setTimeout(() => {
                intro.style.opacity = 0;
            }, 2000);
            setTimeout(() => {
                loop.style.opacity = 1;
            }, 5000);
        }
        if (onlyAt) {
            setTimeout(() => {
                onlyAt.style.opacity = 1;
            }, 3000);
        }
        if (coming) {
            setTimeout(() => {
                coming.style.opacity = 1;
            }, 4000);
        }
    }, []);
    return (
        <>
            <Head>
                <title>Behind the Streams</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main className={styles.main}>
                <video
                    src='/loop.mp4'
                    className={styles.loop}
                    id='loop'
                    autoPlay
                    muted
                    loop
                />
                <video
                    src='/intro.mp4'
                    className={styles.intro}
                    id='intro'
                    autoPlay
                    muted
                />
                <div className={styles.bg}>
                    <div className={styles.cover}>
                        <img
                            src='/logo.svg'
                            alt=''
                            className={`${styles.logo} ${styles.hidden}`}
                        />
                        <p className={styles.onlyAt} id='onlyAt'>
                            ONLY AT <strong>CANNES LIONS</strong>
                        </p>
                        <div className={styles.title}>
                            <h1 className={styles.mainTitle}>
                                Behind the Streams
                            </h1>
                            <h3 className={`${styles.date} ${styles.hidden}`}>
                                20-22 June 2023
                            </h3>
                        </div>
                        <p className={styles.coming} id='coming'>
                            COMING JUNE 20-22
                        </p>
                        <div className={`${styles.foot} ${styles.hidden}`}>
                            <h3 className={styles.cannesLions}>
                                Netflix at Cannes Lions
                            </h3>
                            <h3 className={styles.international}>
                                International Festival of Creativity
                            </h3>
                            <img
                                src='/down.svg'
                                alt=''
                                className={styles.down}
                                onClick={() => {
                                    const content =
                                        document.getElementById('content');
                                    content.scrollIntoView({
                                        behavior: 'smooth',
                                    });
                                }}
                            />
                        </div>
                    </div>
                    <div
                        className={`${styles.content} ${styles.hidden}`}
                        id='content'
                    >
                        <h4 className={styles.behindTheStreams}>
                            Behind the Streams
                        </h4>
                        <p>20-22 June 2023</p>
                        <br />
                        <p className={styles.firstP}>
                            Each year, Cannes Lions brings together people who
                            believe in the power of creativity from across the
                            globe, for a week of celebrating, exploring,
                            learning and networking.
                        </p>
                        <p className={styles.secondP}>
                            Netflix proudly joins the Advertising Market in 2023
                            building on our mission to entertain the world.
                        </p>
                        <div className={styles.mapContainer}>
                            <img src='/map.png' alt='' className={styles.map} />
                        </div>
                        <h4 className={styles.address}>Address:</h4>
                        <p className={styles.thirdP}>
                            <strong>
                                Netflix Space on the Rooftop of the JW Marriott
                                Cannes
                            </strong>
                            <br />
                            Theater Entrance, 3 Rue Frédéric Amouretti 06400
                            Cannes
                        </p>
                        <p className={styles.fourthP}>
                            Open for meetings daily by invite/request only
                        </p>
                        <div className={styles.logos}>
                            <img src='/logo.svg' alt='' />
                            <img src='/cannes-lions-logo.png' alt='' />
                        </div>
                    </div>
                </div>
            </main>
        </>
    );
}
